### ISSUE TITLE
schema parser does not support single line comments

### ISSUE THREAD

**Issue by bkcsfi** [dailymotion/tartiflette#201]
## Report a bug

Please provide

* [ ] **schema parser should accept files that contain single line comments**
* [ ] **Tartiflette version:** _0.7.3_
* [ ] **Python version:** _3.7.1_
* [ ] **Executed in docker:** _No_
* [ ] **GraphQL Schema & Query:** _e.g gist, pastebin or directly the query_
```graphql
type Bug {
    id: Int! # this is required
}
```
* [ ] **Is it a regression from a previous versions?** _unknown_
* [ ] **Stack trace**
```python
Traceback (most recent call last):
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/bin/manifest-graphql", line 11, in <module>
    load_entry_point('entry-wizard', 'console_scripts', 'manifest-graphql')()
  File "/home/bkc/src/SFI/SFI.Projects.EntryWizard/entry_wizard/manifest_system/scripts/graphql_server.py", line 12, in main
    result = run()
  File "/home/bkc/src/SFI/SFI.Projects.EntryWizard/entry_wizard/graphql/server/app.py", line 59, in run
    engine = get_engine(schema_folder=schema_folder)
  File "/home/bkc/src/SFI/SFI.Projects.EntryWizard/entry_wizard/graphql/server/app.py", line 27, in get_engine
    "entry_wizard.graphql.resolvers.vendor",
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/lib/python3.7/site-packages/tartiflette/engine.py", line 57, in __init__
    schema_name, custom_default_resolver, exclude_builtins_scalars
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/lib/python3.7/site-packages/tartiflette/schema/bakery.py", line 41, in bake
    schema = SchemaBakery._preheat(schema_name, exclude_builtins_scalars)
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/lib/python3.7/site-packages/tartiflette/schema/bakery.py", line 21, in _preheat
    build_graphql_schema_from_sdl(sdl, schema=schema)
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/lib/python3.7/site-packages/tartiflette/sdl/builder.py", line 30, in build_graphql_schema_from_sdl
    sdl, parse_graphql_sdl_to_ast(sdl), schema=schema
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/lib/python3.7/site-packages/tartiflette/sdl/builder.py", line 53, in parse_graphql_sdl_to_ast
    return gqlsdl(sdl)
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/lib/python3.7/site-packages/lark/lark.py", line 223, in parse
    return self.parser.parse(text)
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/lib/python3.7/site-packages/lark/parser_frontends.py", line 38, in parse
    return self.parser.parse(token_stream, *[sps] if sps is not NotImplemented else [])
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 82, in parse
    _action, arg = get_action('$END')
  File "/home/bkc/PythonEnvironments/SFI.Projects.EntryWizard/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 49, in get_action
    raise UnexpectedToken(token, expected, state=state)  # TODO filter out rules from expected
lark.exceptions.UnexpectedToken: Unexpected token Token(BANG, '!') at line 1, column 3985.
Expected: SCHEMA, IDENT, TYPE, UNION, SCALAR, INTERFACE, MUTATION, RPAR, ENUM, STRING, QUERY, INPUT, LONG_STRING, TYPE_SYSTEM_DIRECTIVE_LOCATION, IMPLEMENTS, AT, EQUAL, DIRECTIVE, SUBSCRIPTION, RBRACE, EXTEND, ON, RSQB
```

see https://graphql.github.io/graphql-spec/June2018/#sec-Comments

perhaps this is a feature request?

**Comment by tsunammis** [comment]
@bkcsfi Thank you for your bug report. We will analyze it during the next days. 

[Do not hesitate to join the Slack channel](http://slack-tartiflette-io.herokuapp.com/)

**Comment by abusi** [comment]
@bkcsfi can you provide the complete sdl that is failing? your snippet seems to work fine on my setup :tm:

**Comment by bkcsfi** [comment]
sorry I was out of the office and could not reply in a timely manner. Sounds like you were able to recreate?

**Comment by abusi** [comment]
Yeah, it was due to a trick done to the result of the sdl loaded from a file (my first test was using a string in code, and was working). Before 0.8.6, when a SDL was loaded, it was "one lined" because our first version of the lark grammar was not complete and didn't support '\n' as expected. When that was resolved, we forget to "un-onelined" the loaded sdl. 
Basicly when adding a `# comment` everything after was in the comment, regardless of the `\n`. 
Now everything works fine.

Thanks for this bug report !
